version: 2
updates:
  # Dependencias de Maven (Java / Spring Boot)
  - package-ecosystem: "maven"
    directory: "/" # raíz del proyecto, donde está pom.xml
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      # Ignorar cualquier versión que no sea estable de Spring Boot 3
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        versions:
          - "3.0.0-alpha*"  # ignora alphas
          - "3.0.0-beta*"   # ignora betas
          - "3.0.0-rc*"     # ignora release candidates

  # Dependencias de Dockerfile
  - package-ecosystem: "docker"
    directory: "/" # raíz, si tu Dockerfile está ahí
    schedule:
      interval: "weekly"

  # Dependencias de docker-compose
  - package-ecosystem: "docker-compose"
    directory: "/" # raíz, donde está docker-compose.yaml
    schedule:
      interval: "weekly"

  # Dependencias de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # workflows en .github/workflows
    schedule:
      interval: "weekly"