# Nombre de la aplicacion
spring.application.name=${NombreAplicacion:E-commerce_Beer}
server.port=${PuertoServidor:8080}
#spring.profiles.active=dev

# Propiedades para el tamanno de las imagenes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuracion de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# REMEMBER ME CONFIGURATION
security.rememberme.key=${REMEMBER_ME_KEY:12345}
security.rememberme.token-validity=${REMEMBER_ME_TOKEN}

# Ajustes del JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Poblar base de datos
#spring.sql.init.mode=always
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql, classpath:sql/empresa.sql, classpath:sql/usuario.sql, classpath:sql/producto.sql, classpath:sql/blog.sql, classpath:sql/comentario.sql, classpath:sql/compra-2020.sql, classpath:sql/compra-2021.sql, classpath:sql/compra-2022.sql, classpath:sql/compra-2023.sql, classpath:sql/compra-2024.sql, classpath:sql/compra-2025.sql, classpath:sql/factura-proveedor.sql, classpath:sql/peticiones.sql

# Configuracion del pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Configuracion de IA
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=${OPENAI_BASE_URL:"http://localhost:11434/"}
spring.ai.ollama.chat.options.model=${OPENAI_MODEL:"gemma3:latest"}
spring.ai.ollama.chat.options.temperature=0.2
app.ai.negacion-respuesta = ${NEGATIVEANSWERS_APP_AI:"Hola"}

## Activar memoria con JDBC
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
## Usa el schema por defecto de Spring AI (recomendado)
#spring.ai.chat.memory.repository.jdbc.schema=${JDBC_SCHEMA_CHAT_MEMORY}

# Configuracion JWT
security.jwt.key.private=${JWT_SECRET_ECOMMERCE:LLAVE_TEMP_DEV}
security.jwt.user.generator=${JWT_ISSUER_ECOMMERCE:USER_TEMP_DEV}

# Secret key reRECPTCHA Google v2 - invisible
spring.google.recaptcha.url=${PASSWORD_URL_RECAPTCHA:https://www.google.com/recaptcha/api/siteverify}
spring.google.recaptcha.secret-key=${PASSWORD_KEY_RECAPTCHA}

# OAuth2 Client Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.user-name-attribute=email

# Detalles del servidor SMTP para Java Mail Sender (se usa para el servidor de Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.default-encoding=UTF-8
spring.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true

# Credenciales Cloudinary
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}

# Credenciales Mercado Pago
mercado_pago.access_token=${MERCADO_PAGO_ACCESS_TOKEN:ACCESS_TOKEN}

# Errores personalizados
server.error.whitelabel.enabled=false
server.servlet.session.tracking-modes=cookie
spring.web.error.whitelabel.enabled=false
spring.web.error.path=/error
spring.web.error.include-message=always